add bookmark conventions and improve profile
pdsinterop/conventions pull request #5
Opened 2023-08-15 11:36 UTC by soltanireza65

for the profile, I've used inrupt's sample app as a reference 
and for the bookmarks, I've looked a look at `https://github.com/mark-book/markbook`

2023-08-24 09:07 UTC, michielbdejong requested changes

2023-08-24 09:07 UTC, michielbdejong commented on bookmark.md
> +# Notepad
what does bookmark have to do with bookmarks? copy-paste error maybe?

2023-08-24 09:07 UTC, michielbdejong commented on bookmark.md
> +_NB: this currently mainly describes how Solid OS stores data on a Solid Pod._
what about mark-book, then?

2023-08-25 06:51 UTC, soltanireza65 commented on bookmark.md
> +# Notepad
fixed

2023-08-25 06:52 UTC, soltanireza65 commented on bookmark.md
> +_NB: this currently mainly describes how Solid OS stores data on a Solid Pod._
fixed

2023-08-25 08:28 UTC, merged